robot_frame = est_robot.getPose();
% translate goal pose to robot frame
goal_pose_in_rf = pose(pose.matToPoseVec(robot_frame.bToA()*goal_pose.bToA()));
trajectory.generateTraj(goal_pose_in_rf.x(),...
                        goal_pose_in_rf.y(),...
                        goal_pose_in_rf.th(),...
                        1,0.2);
execute_trajectory